In [2]:
!pip install tensorflow

  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4829 sha256=6233b6399ce3de8014ffdb25c13e5ee4f4d1b7ef6f894f28e8cfbba81816e906
  Stored in directory: c:\users\maxim\appdata\local\pip\cache\wheels\a0\16\9c\5473df82468f958445479c59e784896fa24f4a5fc024b0f501
Successfully built termcolor
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 3.10.0
    Uninstalling importlib-metadata-3.10.0:
      Successfully uninstalled importlib-metadata-3.10.0


### I'm learning with Tensorflow Tutorial by Ren Zhang

In [3]:
import numpy as np
import tensorflow as tf
from pprint import pprint # prints objects nicely
print(tf.__version__)
tf.random.set_seed(42)


2.7.0


### Tensors

In [6]:
scalar = tf.constant(1, dtype=tf.int8)
vector = tf.constant([1, 2, 3], dtype=tf.float32)
matrix = tf.constant(np.array([[1, 2], [3, 4]]), dtype=tf.float32)
pprint([scalar, vector, matrix])

[<tf.Tensor: shape=(), dtype=int8, numpy=1>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>]


In [7]:
print(matrix.shape)
pprint(tf.shape(matrix))
print(id(matrix))

(2, 2)
<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2])>
2227990556336


In [9]:
# tf.cast applys aperation
matrix = tf.cast(matrix, dtype=tf.int8)
pprint(matrix)
print(id(matrix))
# new id -> new tensor object

<tf.Tensor: shape=(2, 2), dtype=int8, numpy=
array([[1, 2],
       [3, 4]], dtype=int8)>
2227990582896


In [10]:
o = tf.zeros((2, 2))
x = tf.random.uniform((3, 2))
pprint(o)
pprint(x)
pprint(tf.ones_like(o))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>
<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.6645621 , 0.44100678],
       [0.3528825 , 0.46448255],
       [0.03366041, 0.68467236]], dtype=float32)>
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>


In [11]:
x_numpy = x.numpy()
print(type(x_numpy))

<class 'numpy.ndarray'>


#### Copying to deivces

In [12]:
print(x.device)

/job:localhost/replica:0/task:0/device:CPU:0


In [13]:
with tf.device('/cpu:0'):
    x_cpu = tf.identity(x)
with tf.device('/gpu:0'):
    x_gpu = tf.identity(x) # he can't find my gpu for some reason
print(x_cpu.device)
print(x_gpu.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0


### Operations

take tensors as inputs and give tensors as outputs

basic math ops are overloaded by tensor ops

In [15]:
e = tf.random.uniform((3, 2), dtype=x.dtype)
pprint(tf.math.reduce_all(x.__add__(e) == tf.add(x, e)))

<tf.Tensor: shape=(), dtype=bool, numpy=True>


In [18]:
pprint(tf.math.reduce_all(x.__mul__(e) == tf.multiply(x, e)))

<tf.Tensor: shape=(), dtype=bool, numpy=True>


In [20]:
pprint(tf.math.reduce_all(x.__matmul__(tf.transpose(e)) == tf.linalg.matmul(x, e, transpose_b=True)))

<tf.Tensor: shape=(), dtype=bool, numpy=True>


In [21]:
#indexing is similar to numpy
pprint(matrix[0, 1])
pprint(matrix[1, :2])
pprint(matrix[tf.newaxis, 1, :2])

<tf.Tensor: shape=(), dtype=int8, numpy=2>
<tf.Tensor: shape=(2,), dtype=int8, numpy=array([3, 4], dtype=int8)>
<tf.Tensor: shape=(1, 2), dtype=int8, numpy=array([[3, 4]], dtype=int8)>


In [28]:
a = tf.constant([3, 6])
b = tf.constant([2, 2])
pprint(tf.add(a, b))
pprint(tf.add_n([a, b, b]))
pprint(tf.multiply(a, b)) #elementwise multiplication
#pprint(tf.matmul(a, b)) #error bc matrix multiplication
pprint(tf.matmul(tf.reshape(a, [1, 2]), tf.reshape(b, [2, 1])))
pprint(tf.divide(a, b))
pprint(tf.math.subtract(a, b))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 8])>
<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>
<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 6, 12])>
<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[18]])>
<tf.Tensor: shape=(2,), dtype=float64, numpy=array([1.5, 3. ])>
<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4])>


### Variables

tensors are immutable

In [30]:
v = tf.Variable(x)
pprint(v)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[0.6645621 , 0.44100678],
       [0.3528825 , 0.46448255],
       [0.03366041, 0.68467236]], dtype=float32)>


In [31]:
# operators work same. output is a tensor!
pprint(tf.square(v))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.4416428 , 0.19448698],
       [0.12452606, 0.21574403],
       [0.00113302, 0.46877623]], dtype=float32)>


In [32]:
#var update
v.assign(tf.square(v))
pprint(v)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[0.4416428 , 0.19448698],
       [0.12452606, 0.21574403],
       [0.00113302, 0.46877623]], dtype=float32)>


In [33]:
# also .assign_sub and .assign_add
v.assign_sub(1 * tf.ones_like(v, dtype=v.dtype))
pprint(v)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[-0.55835724, -0.805513  ],
       [-0.8754739 , -0.784256  ],
       [-0.998867  , -0.5312238 ]], dtype=float32)>


#### Vars are typically used to represent parameters and states of the model

### Automatic Differentiation

tf.GradientTape context helps to trace what happens inside to calc gradients

In [34]:
a = tf.Variable([4], dtype=tf.float32)
b = tf.Variable([5], dtype=tf.float32)

def f(a, b, power=2, d=3):
    return tf.pow(a, power) + d * b

with tf.GradientTape(watch_accessed_variables=True) as tape:
    c = f(a, b)
pprint(tape.gradient(target=c, sources=[a, b]))

[<tf.Tensor: shape=(1,), dtype=float32, numpy=array([8.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.], dtype=float32)>]


In [36]:
# we can also asc gradient to watch tensors too
d = tf.constant(3, dtype=tf.float32)
with tf.GradientTape() as tape:
    tape.watch(d)
    c = f(a, b, d=d)
pprint(tape.gradient(target=c, sources=[d]))

[<tf.Tensor: shape=(), dtype=float32, numpy=5.0>]


In [37]:
with tf.GradientTape() as tape:
    c = f(a, b)
pprint(tape.gradient(c, [a]))
pprint(tape.gradient(c, [b]))
# once we extact gradient from tape it will be released

[<tf.Tensor: shape=(1,), dtype=float32, numpy=array([8.], dtype=float32)>]


RuntimeError: A non-persistent GradientTape can only be used to compute one set of gradients (or jacobians)

In [38]:
with tf.GradientTape(persistent=True) as tape: # persistent allows to use it multiple times. better del after
    c = f(a, b)
pprint(tape.gradient(c, [a]))
pprint(tape.gradient(c, [b]))
del tape

[<tf.Tensor: shape=(1,), dtype=float32, numpy=array([8.], dtype=float32)>]
[<tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.], dtype=float32)>]


### Linear Regression

With tensors, variables, operations and automatic differentiation, we can start building
models. Let's train a linear regression model with the gradient descent algorithm.

In [42]:
# grount truth
true_weights = tf.constant(list(range(5)), dtype=tf.float32)[:, tf.newaxis]

# random training data
x = tf.constant(tf.random.uniform((32, 5)), dtype=tf.float32)
y = tf.constant(x @ true_weights, dtype=tf.float32) # what is @? prob matmul

# parametes
weights = tf.Variable(tf.random.uniform((5, 1)), dtype=tf.float32)

for iteration in range(1001):
    with tf.GradientTape() as tape:
        y_hat = tf.linalg.matmul(x, weights)
        loss = tf.reduce_mean(tf.square(y-y_hat))
        
    if not iteration % 100:
        print('MSE at it {:4d} is {:5.4f}'.format(iteration, loss))

    gradients = tape.gradient(loss, weights)
    weights.assign_add(-0.05 * gradients)
pprint(weights)

MSE at it    0 is 18.9390
MSE at it  100 is 0.1633
MSE at it  200 is 0.0389
MSE at it  300 is 0.0104
MSE at it  400 is 0.0030
MSE at it  500 is 0.0009
MSE at it  600 is 0.0003
MSE at it  700 is 0.0001
MSE at it  800 is 0.0000
MSE at it  900 is 0.0000
MSE at it 1000 is 0.0000
<tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[2.7718204e-03],
       [9.9988103e-01],
       [2.0038643e+00],
       [2.9949045e+00],
       [3.9986048e+00]], dtype=float32)>


## AutoGraph